/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     4/29/2025 11:57:16 PM                        */
/*==============================================================*/

/* Xóa các bảng nếu tồn tại */
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS EQUIPMENT;
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS MATERIALS;
DROP TABLE IF EXISTS MATERIAL_ORDERS;
DROP TABLE IF EXISTS MATERIAL_TYPES;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS PRODUCTION_MATERIALS;
DROP TABLE IF EXISTS PRODUCTION_PLANS;
DROP TABLE IF EXISTS PRODUCTION_STEPS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS QUALITY_CONTROL;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS SUPPLIERS;
DROP TABLE IF EXISTS USERS;

/* Tạo các bảng */
CREATE TABLE CART (
    ID_CART INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_PRODUCT INT NOT NULL COMMENT '',
    ID_USERS INT NOT NULL COMMENT '',
    CREATED_AT_CART DATETIME COMMENT '',
    PRIMARY KEY (ID_CART)
);

CREATE TABLE CATEGORIES (
    ID_CATEGORIES_ INT NOT NULL AUTO_INCREMENT COMMENT '',
    NAME_CATEGORIES_ VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_CATEGORIES_)
);

CREATE TABLE EQUIPMENT (
    ID_EQUIPMENT INT NOT NULL AUTO_INCREMENT COMMENT '',
    NAME_EQUIPMENT VARCHAR(255) COMMENT '',
    TYPE_EQUIPMENT VARCHAR(255) COMMENT '',
    STATUS VARCHAR(255) COMMENT '',
    LAST_MAINTENANCE VARCHAR(255) COMMENT '',
    CREATED_AT DATETIME COMMENT '',
    UPDATED_AT DATETIME COMMENT '',
    PRIMARY KEY (ID_EQUIPMENT)
);

CREATE TABLE INVENTORY (
    ID_INVENTORY_ INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_MATERIALS_ INT NOT NULL COMMENT '',
    QUANTITY_INVENTORY INT COMMENT '',
    LAST_UPDATED_ DATETIME COMMENT '',
    STORAGE_CONDITION VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_INVENTORY_)
);

CREATE TABLE MATERIALS (
    ID_MATERIALS_ INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_MATERIAL_TYPES INT NOT NULL COMMENT '',
    NAME_ VARCHAR(255) COMMENT '',
    UNIT_ VARCHAR(255) COMMENT '',
    COST_PER_UNIT_ FLOAT COMMENT '',
    CREATED_AT_PRODUCTS DATETIME COMMENT '',
    UPDATED_AT_PRODUCTS DATETIME COMMENT '',
    ORIGIN VARCHAR(255) COMMENT '',
    EXPIRY_DATE DATETIME COMMENT '',
    PRIMARY KEY (ID_MATERIALS_)
);

CREATE TABLE MATERIAL_ORDERS (
    ID_MATERIAL_ORDER INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_MATERIALS_ INT NOT NULL COMMENT '',
    ID_SUPPLIERS INT NOT NULL COMMENT '',
    QUANTITY_ORDERED INT COMMENT '',
    ORDER_DATE DATETIME COMMENT '',
    DELIVERY_DATE DATETIME COMMENT '',
    STATUS VARCHAR(255) COMMENT '',
    TOTAL_COST FLOAT COMMENT '',
    PRIMARY KEY (ID_MATERIAL_ORDER)
);

CREATE TABLE MATERIAL_TYPES (
    ID_MATERIAL_TYPES INT NOT NULL AUTO_INCREMENT COMMENT '',
    NAME_MATERIAL_TYPES VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_MATERIAL_TYPES)
);

CREATE TABLE ORDERS (
    ID_ORDERS_ INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_USERS INT NOT NULL COMMENT '',
    DATE_ORDER DATETIME COMMENT '',
    TOTAL_AMOUNT_ORDER FLOAT COMMENT '',
    PAYMENT_STATUS_ORDER VARCHAR(255) COMMENT '',
    SHIPPING_STATUS_ORDER VARCHAR(255) COMMENT '',
    SHIPPING_ADDRESS VARCHAR(255) COMMENT '',
    SHIPPING_METHOD VARCHAR(255) COMMENT '',
    SHIPPING_COST VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_ORDERS_)
);

CREATE TABLE ORDER_ITEMS (
    ID_ORDER_ITEMS INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_PRODUCT INT NOT NULL COMMENT '',
    ID_ORDERS_ INT NOT NULL COMMENT '',
    QUANTITY_INVENTORY INT COMMENT '',
    PRICE_ORDER_ITEMS FLOAT COMMENT '',
    PRIMARY KEY (ID_ORDER_ITEMS)
);

CREATE TABLE PRODUCTION_MATERIALS (
    ID_PRODUCT_MATERIALS INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_PRODUCTION_PLANS INT NOT NULL COMMENT '',
    ID_MATERIALS_ INT NOT NULL COMMENT '',
    QUANTITY_PER_UNIT_PRODUCT_MATERIALS FLOAT COMMENT '',
    UNIT_PRODUCT_MATERIALS VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_PRODUCT_MATERIALS)
);

CREATE TABLE PRODUCTION_PLANS (
    ID_PRODUCTION_PLANS INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_PRODUCT INT NOT NULL COMMENT '',
    ID_USERS INT NOT NULL COMMENT '',
    PLANNED_START_PRODUCTION_PLANS DATETIME COMMENT '',
    PLANNED_END_PRODUCTION_PLANS DATETIME COMMENT '',
    ACTUAL_START_PRODUCTION_PLANS DATETIME COMMENT '',
    ACTUAL_END_PRODUCTION_PLANS DATETIME COMMENT '',
    STATUS_PRODUCTION_PLANS VARCHAR(255) COMMENT '',
    NOTE_PRODUCTION_PLANS TEXT COMMENT '',
    PRIMARY KEY (ID_PRODUCTION_PLANS)
);

CREATE TABLE PRODUCTION_STEPS (
    ID_PRODUCTION_STEPS_ INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_PRODUCTION_PLANS INT NOT NULL COMMENT '',
    ID_USERS INT NOT NULL COMMENT '',
    ID_EQUIPMENT INT NOT NULL COMMENT '',
    STEP_NAME_PRODUCTION_STEPS VARCHAR(255) COMMENT '',
    START_TIME_PRODUCTION_STEPS DATETIME COMMENT '',
    END_TIME_PRODUCTION_STEPS DATETIME COMMENT '',
    STATUS_PRODUCTION_STEPS VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_PRODUCTION_STEPS_)
);

CREATE TABLE PRODUCTS (
    ID_PRODUCT INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_CATEGORIES_ INT NOT NULL COMMENT '',
    NAME_PRODUCTS VARCHAR(255) COMMENT '',
    DESCRIPTION_PRODUCTS VARCHAR(255) COMMENT '',
    PRICE_PRODUCTS FLOAT COMMENT '',
    STOCK_PRODUCTS INT COMMENT '',
    IMAGE_URL_PRODUCTS VARCHAR(255) COMMENT '',
    CREATED_AT_PRODUCTS DATETIME COMMENT '',
    UPDATED_AT_PRODUCTS DATETIME COMMENT '',
    PRIMARY KEY (ID_PRODUCT)
);

CREATE TABLE QUALITY_CONTROL (
    ID_QUALITY_CONTROL INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_PRODUCTION_STEPS_ INT NOT NULL COMMENT '',
    ID_PRODUCT INT NOT NULL COMMENT '',
    ID_USERS INT NOT NULL COMMENT '',
    CHECK_DATE DATETIME COMMENT '',
    RESULT VARCHAR(255) COMMENT '',
    NOTE TEXT COMMENT '',
    PRIMARY KEY (ID_QUALITY_CONTROL)
);

CREATE TABLE ROLE (
    ID_ROLE INT NOT NULL AUTO_INCREMENT COMMENT '',
    NAME_ROLE VARCHAR(255) COMMENT '',
    LIST_PERMISION VARCHAR(255) COMMENT '',
    IS_DELETE BOOL COMMENT '',
    CODE_NAME VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_ROLE)
);

CREATE TABLE SUPPLIERS (
    ID_SUPPLIERS INT NOT NULL AUTO_INCREMENT COMMENT '',
    NAME_PRODUCTS VARCHAR(255) COMMENT '',
    ADDRESS_SUPPLIERS VARCHAR(255) COMMENT '',
    PHONE_SUPPLIERS INT COMMENT '',
    EMAIL_SUPPLIERS VARCHAR(255) COMMENT '',
    CREATED_AT_SUPPLIERS DATETIME COMMENT '',
    UPDATED_AT_SUPPLIERS DATETIME COMMENT '',
    STATUS_SUPPLIERS VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_SUPPLIERS)
);

CREATE TABLE USERS (
    ID_USERS INT NOT NULL AUTO_INCREMENT COMMENT '',
    ID_ROLE INT NOT NULL COMMENT '',
    NAME_USERS VARCHAR(255) COMMENT '',
    EMAIL_USERS VARCHAR(255) COMMENT '',
    _PASSWORD_HASH_USERS VARCHAR(255) COMMENT '',
    PHONE_USERS INT COMMENT '',
    IS_ACTIVE_USERS VARCHAR(255) COMMENT '',
    CREATED_AT_USERS DATETIME COMMENT '',
    UPDATED_AT_USERS DATETIME COMMENT '',
    IS_DELETE_USERS VARCHAR(255) COMMENT '',
    PRIMARY KEY (ID_USERS)
);

/* Thêm các ràng buộc khóa ngoại */
ALTER TABLE CART ADD CONSTRAINT FK_CART_ASSOCIATI_PRODUCTS FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCTS (ID_PRODUCT) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CART ADD CONSTRAINT FK_CART_ASSOCIATI_USERS FOREIGN KEY (ID_USERS)
    REFERENCES USERS (ID_USERS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE INVENTORY ADD CONSTRAINT FK_INVENTOR_ASSOCIATI_MATERIAL FOREIGN KEY (ID_MATERIALS_)
    REFERENCES MATERIALS (ID_MATERIALS_) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATERIALS ADD CONSTRAINT FK_MATERIAL_ASSOCIATI_MATERIAL_TYPE FOREIGN KEY (ID_MATERIAL_TYPES)
    REFERENCES MATERIAL_TYPES (ID_MATERIAL_TYPES) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATERIAL_ORDERS ADD CONSTRAINT FK_MATERIAL_ORDERS_ASSOCIATI_SUPPLIER FOREIGN KEY (ID_SUPPLIERS)
    REFERENCES SUPPLIERS (ID_SUPPLIERS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATERIAL_ORDERS ADD CONSTRAINT FK_MATERIAL_ORDERS_ASSOCIATI_MATERIAL FOREIGN KEY (ID_MATERIALS_)
    REFERENCES MATERIALS (ID_MATERIALS_) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_ASSOCIATI_USERS FOREIGN KEY (ID_USERS)
    REFERENCES USERS (ID_USERS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORDER_ITEMS ADD CONSTRAINT FK_ORDER_IT_ASSOCIATI_ORDERS FOREIGN KEY (ID_ORDERS_)
    REFERENCES ORDERS (ID_ORDERS_) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORDER_ITEMS ADD CONSTRAINT FK_ORDER_IT_ASSOCIATI_PRODUCTS FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCTS (ID_PRODUCT) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTION_MATERIALS ADD CONSTRAINT FK_PRODUCTI_ASSOCIATI_MATERIAL FOREIGN KEY (ID_MATERIALS_)
    REFERENCES MATERIALS (ID_MATERIALS_) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTION_MATERIALS ADD CONSTRAINT FK_PRODUCTI_ASSOCIATI_PRODUCTI FOREIGN KEY (ID_PRODUCTION_PLANS)
    REFERENCES PRODUCTION_PLANS (ID_PRODUCTION_PLANS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTION_PLANS ADD CONSTRAINT FK_PRODUCTI_ASSOCIATI_USERS FOREIGN KEY (ID_USERS)
    REFERENCES USERS (ID_USERS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTION_PLANS ADD CONSTRAINT FK_PRODUCTI_ASSOCIATI_PRODUCTS FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCTS (ID_PRODUCT) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTION_STEPS ADD CONSTRAINT FK_PRODUCTI_ASSOCIATI_USERS FOREIGN KEY (ID_USERS)
    REFERENCES USERS (ID_USERS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTION_STEPS ADD CONSTRAINT FK_PRODUCTI_ASSOCIATI_EQUIPMEN FOREIGN KEY (ID_EQUIPMENT)
    REFERENCES EQUIPMENT (ID_EQUIPMENT) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTION_STEPS ADD CONSTRAINT FK_PRODUCTI_ASSOCIATI_PRODUCTI FOREIGN KEY (ID_PRODUCTION_PLANS)
    REFERENCES PRODUCTION_PLANS (ID_PRODUCTION_PLANS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_ASSOCIATI_CATEGORI FOREIGN KEY (ID_CATEGORIES_)
    REFERENCES CATEGORIES (ID_CATEGORIES_) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QUALITY_CONTROL ADD CONSTRAINT FK_QUALITY__ASSOCIATI_USERS FOREIGN KEY (ID_USERS)
    REFERENCES USERS (ID_USERS) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QUALITY_CONTROL ADD CONSTRAINT FK_QUALITY__ASSOCIATI_PRODUCTS FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCTS (ID_PRODUCT) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE QUALITY_CONTROL ADD CONSTRAINT FK_QUALITY__ASSOCIATI_PRODUCTI FOREIGN KEY (ID_PRODUCTION_STEPS_)
    REFERENCES PRODUCTION_STEPS (ID_PRODUCTION_STEPS_) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_ASSOCIATI_ROLE FOREIGN KEY (ID_ROLE)
    REFERENCES ROLE (ID_ROLE) ON DELETE RESTRICT ON UPDATE RESTRICT;